modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="tchineseb"
version="${mod_version}"
displayName="ChineseBridge"
authors="OpenSanctum"
description='''自動補齊簡體中文、中文（台灣）與中文（香港）缺少的語系資源。'''

[[dependencies.tchineseb]]
modId="neoforge"
type="required"
versionRange="[20.2,)"
ordering="NONE"
side="CLIENT"

[[dependencies.tchineseb]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
