modLoader="javafml"
loaderVersion="[1,)"
license="CC0-1.0"

[[mods]]
modId="tchineseb"
version="001"
displayName="Traditional Chinese Bridge"
authors="RainBlueTW"
description='''自動將簡體中文語系轉換並整合成繁體中文資源包。'''

[[dependencies.tchineseb]]
modId="neoforge"
type="required"
versionRange="[20.2,)"
ordering="NONE"
side="CLIENT"

[[dependencies.tchineseb]]
modId="minecraft"
type="required"
versionRange="[1.20.2,26.3)"
ordering="NONE"
side="CLIENT"
